export const AVAILABLE_USER_PERMISSIONS = [
  "VIEW_DASHBOARD",
  "VIEW_OWN_PROFILE",
  "VIEW_OWN_SCHEDULE",
  "VIEW_NOTIFICATIONS",
  "MANAGE_NOTIFICATIONS",
  "VIEW_COMMUNICATION_CENTER",
  "MANAGE_COMMUNICATION_CENTER",
  "VIEW_TEACHER_DAILY_AGENDA",
  "MANAGE_TEACHER_DAILY_AGENDA",
  "VIEW_STUDENT_BASIC_DATA",
  "VIEW_STUDENT_CONTACT_DATA",
  "VIEW_STUDENT_ACADEMIC_DATA",
  "VIEW_STUDENT_FINANCIAL_DATA",
  "VIEW_STUDENT_SENSITIVE_DATA",
  "VIEW_STUDENT_ACCESS_DATA",
  "VIEW_TEACHER_BASIC_DATA",
  "VIEW_TEACHER_CONTACT_DATA",
  "VIEW_TEACHER_ACADEMIC_DATA",
  "VIEW_TEACHER_FINANCIAL_DATA",
  "VIEW_TEACHER_SENSITIVE_DATA",
  "VIEW_TEACHER_ACCESS_DATA",
  "VIEW_GUARDIAN_BASIC_DATA",
  "VIEW_GUARDIAN_CONTACT_DATA",
  "VIEW_GUARDIAN_FINANCIAL_DATA",
  "VIEW_GUARDIAN_SENSITIVE_DATA",
  "VIEW_GUARDIAN_ACCESS_DATA",
  "VIEW_FINANCIAL",
  "MANAGE_FINANCIAL",
  "ISSUE_BOLETOS",
  "MANAGE_MONTHLY_FEES",
  "VIEW_CASHIER",
  "RECEIVE_PAYMENTS",
  "SETTLE_RECEIVABLES",
  "CLOSE_CASHIER",
  "VIEW_USERS",
  "MANAGE_SERIES",
  "VIEW_SERIES",
  "MANAGE_TEACHERS",
  "VIEW_TEACHERS",
  "MANAGE_STUDENTS",
  "VIEW_STUDENTS",
  "MANAGE_GUARDIANS",
  "VIEW_GUARDIANS",
  "MANAGE_SUBJECTS",
  "VIEW_SUBJECTS",
  "MANAGE_CLASSES",
  "VIEW_CLASSES",
  "MANAGE_SERIES_CLASSES",
  "VIEW_SERIES_CLASSES",
  "MANAGE_ENROLLMENTS",
  "VIEW_ENROLLMENTS",
  "MANAGE_SCHEDULES",
  "VIEW_SCHEDULES",
  "MANAGE_CLASS_SCHEDULES",
  "VIEW_CLASS_SCHEDULES",
  "MANAGE_LESSON_CALENDARS",
  "VIEW_LESSON_CALENDARS",
  "MANAGE_SCHOOL_YEARS",
  "VIEW_SCHOOL_YEARS",
  "MANAGE_USERS",
] as const;

export type UserPermission = (typeof AVAILABLE_USER_PERMISSIONS)[number];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, UserPermission[]> = {
  ADMIN: [...AVAILABLE_USER_PERMISSIONS],
  SECRETARIA: [
    "VIEW_DASHBOARD",
    "VIEW_NOTIFICATIONS",
    "MANAGE_NOTIFICATIONS",
    "VIEW_COMMUNICATION_CENTER",
    "VIEW_TEACHERS",
    "VIEW_STUDENTS",
    "VIEW_GUARDIANS",
    "VIEW_STUDENT_BASIC_DATA",
    "VIEW_STUDENT_CONTACT_DATA",
    "VIEW_STUDENT_ACADEMIC_DATA",
    "VIEW_STUDENT_SENSITIVE_DATA",
    "VIEW_STUDENT_ACCESS_DATA",
    "VIEW_TEACHER_BASIC_DATA",
    "VIEW_TEACHER_CONTACT_DATA",
    "VIEW_TEACHER_ACADEMIC_DATA",
    "VIEW_TEACHER_SENSITIVE_DATA",
    "VIEW_TEACHER_ACCESS_DATA",
    "VIEW_GUARDIAN_BASIC_DATA",
    "VIEW_GUARDIAN_CONTACT_DATA",
    "VIEW_GUARDIAN_SENSITIVE_DATA",
    "VIEW_GUARDIAN_ACCESS_DATA",
    "VIEW_SUBJECTS",
    "VIEW_CLASSES",
    "VIEW_SERIES",
    "VIEW_SERIES_CLASSES",
    "VIEW_ENROLLMENTS",
    "VIEW_SCHEDULES",
    "VIEW_CLASS_SCHEDULES",
    "VIEW_LESSON_CALENDARS",
    "VIEW_SCHOOL_YEARS",
    "MANAGE_STUDENTS",
    "MANAGE_GUARDIANS",
    "MANAGE_CLASSES",
    "MANAGE_SERIES",
    "MANAGE_SERIES_CLASSES",
    "MANAGE_ENROLLMENTS",
  ],
  COORDENACAO: [
    "VIEW_DASHBOARD",
    "VIEW_NOTIFICATIONS",
    "MANAGE_NOTIFICATIONS",
    "VIEW_COMMUNICATION_CENTER",
    "VIEW_TEACHERS",
    "VIEW_STUDENTS",
    "VIEW_GUARDIANS",
    "VIEW_STUDENT_BASIC_DATA",
    "VIEW_STUDENT_CONTACT_DATA",
    "VIEW_STUDENT_ACADEMIC_DATA",
    "VIEW_TEACHER_BASIC_DATA",
    "VIEW_TEACHER_CONTACT_DATA",
    "VIEW_TEACHER_ACADEMIC_DATA",
    "VIEW_TEACHER_SENSITIVE_DATA",
    "VIEW_GUARDIAN_BASIC_DATA",
    "VIEW_GUARDIAN_CONTACT_DATA",
    "VIEW_SUBJECTS",
    "VIEW_CLASSES",
    "VIEW_SERIES",
    "VIEW_SERIES_CLASSES",
    "VIEW_ENROLLMENTS",
    "VIEW_SCHEDULES",
    "VIEW_CLASS_SCHEDULES",
    "VIEW_LESSON_CALENDARS",
    "VIEW_SCHOOL_YEARS",
    "MANAGE_TEACHERS",
    "MANAGE_SUBJECTS",
    "MANAGE_SCHEDULES",
    "MANAGE_CLASS_SCHEDULES",
    "MANAGE_LESSON_CALENDARS",
    "MANAGE_SCHOOL_YEARS",
  ],
  PROFESSOR: [
    "VIEW_DASHBOARD",
    "VIEW_OWN_PROFILE",
    "VIEW_OWN_SCHEDULE",
    "VIEW_NOTIFICATIONS",
    "MANAGE_NOTIFICATIONS",
    "VIEW_COMMUNICATION_CENTER",
    "MANAGE_COMMUNICATION_CENTER",
    "VIEW_TEACHER_DAILY_AGENDA",
    "MANAGE_TEACHER_DAILY_AGENDA",
    "VIEW_TEACHER_BASIC_DATA",
    "VIEW_TEACHER_CONTACT_DATA",
    "VIEW_TEACHER_ACADEMIC_DATA",
    "VIEW_TEACHER_SENSITIVE_DATA",
    "VIEW_TEACHER_ACCESS_DATA",
    "VIEW_STUDENT_BASIC_DATA",
    "VIEW_STUDENT_ACADEMIC_DATA",
    "VIEW_GUARDIAN_BASIC_DATA",
    "VIEW_GUARDIAN_CONTACT_DATA",
  ],
  ALUNO: [
    "VIEW_DASHBOARD",
    "VIEW_OWN_PROFILE",
    "VIEW_OWN_SCHEDULE",
    "VIEW_NOTIFICATIONS",
    "MANAGE_NOTIFICATIONS",
    "VIEW_STUDENT_BASIC_DATA",
    "VIEW_STUDENT_CONTACT_DATA",
    "VIEW_STUDENT_ACADEMIC_DATA",
    "VIEW_STUDENT_SENSITIVE_DATA",
    "VIEW_STUDENT_ACCESS_DATA",
  ],
  RESPONSAVEL: [
    "VIEW_DASHBOARD",
    "VIEW_OWN_PROFILE",
    "VIEW_OWN_SCHEDULE",
    "VIEW_NOTIFICATIONS",
    "MANAGE_NOTIFICATIONS",
    "VIEW_GUARDIAN_BASIC_DATA",
    "VIEW_GUARDIAN_CONTACT_DATA",
    "VIEW_GUARDIAN_FINANCIAL_DATA",
    "VIEW_GUARDIAN_SENSITIVE_DATA",
    "VIEW_GUARDIAN_ACCESS_DATA",
    "VIEW_STUDENT_BASIC_DATA",
    "VIEW_STUDENT_CONTACT_DATA",
    "VIEW_STUDENT_ACADEMIC_DATA",
    "VIEW_STUDENT_FINANCIAL_DATA",
    "VIEW_STUDENT_SENSITIVE_DATA",
  ],
};

export function getDefaultPermissionsForRole(
  role?: string | null,
): UserPermission[] {
  const normalizedRole = String(role || "").trim().toUpperCase();
  return ROLE_DEFAULT_PERMISSIONS[normalizedRole]
    ? [...ROLE_DEFAULT_PERMISSIONS[normalizedRole]]
    : [];
}

export function normalizePermissions(input: unknown): UserPermission[] {
  const raw = Array.isArray(input)
    ? input
    : typeof input === "string"
      ? input.split(",")
      : [];

  const normalized = raw
    .map((item) =>
      String(item || "")
        .trim()
        .toUpperCase(),
    )
    .filter((item): item is UserPermission =>
      AVAILABLE_USER_PERMISSIONS.includes(item as UserPermission),
    );

  return Array.from(new Set(normalized));
}

export function serializePermissions(input: unknown): string | null {
  const normalized = normalizePermissions(input);
  return normalized.length > 0 ? JSON.stringify(normalized) : null;
}

export function deserializePermissions(
  value?: string | null,
  role?: string | null,
): UserPermission[] {
  if (value) {
    try {
      const parsed = JSON.parse(value);
      const normalized = normalizePermissions(parsed);
      if (normalized.length > 0) return normalized;
    } catch {
      const normalized = normalizePermissions(value);
      if (normalized.length > 0) return normalized;
    }
  }

  return getDefaultPermissionsForRole(role);
}
